# Generated by Django 4.2.1 on 2023-05-10 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("coupon", "0002_remove_coupon_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="coupon",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="coupon.user",
            ),
        ),
    ]
