# Generated by Django 4.2.1 on 2023-05-11 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coupon", "0002_alter_comment_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="coupon",
            name="code",
            field=models.IntegerField(default=0),
        ),
    ]
