# Generated by Django 4.2.1 on 2023-05-11 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("coupon", "0003_coupon_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coupon",
            name="code",
        ),
    ]
