# Generated by Django 4.2.1 on 2023-05-11 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coupon", "0004_remove_coupon_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="coupon",
            name="code",
            field=models.CharField(default="Coupon", max_length=32),
        ),
    ]
