# Generated by Django 4.2.1 on 2023-05-11 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coupon", "0005_coupon_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="coupon",
            name="comments_amt",
            field=models.IntegerField(default=0),
        ),
    ]
